import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PostProvider } from "@/Provider/Posts";
import Providers from "@/Provider/ReactQuery";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EasyBuy",
  description: "Generated by create next app",
  icons: "favicon.ico"
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
            {children}
            <Toaster position="top-right" />
        </Providers>
      </body>

    </html>
  );
}
